version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/project2
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "4200:4200"
    depends_on:
      - server

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
