version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - MONGO_URL=${MONGO_URL} # Pass the global MongoDB URL
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - .env
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - API_URL=${API_URL}
    depends_on:
      - server

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
